sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_takeout
    username: root
    password: 1234
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tM7R637hSP6Bg2ChkZb
    access-key-secret: w15PIEw7LidW8F70CtLomm5fJvACTc
    bucket-name: cyj-sky
